#!/bin/bash
set -eux

function base() {
  docker buildx build -t shynhan/dev-environment:base --no-cache $@ base/
}

function latest() {
  docker buildx build -t shynhan/dev-environment:latest --no-cache $@ latest/
}

$@
