name: dev
services:
  dev:
    image: "ghcr.io/synhi/dev-environment:latest"
    container_name: "dev"
    restart: "unless-stopped"
    hostname: "dev"
    tty: true
    network_mode: "bridge"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - root:/root

volumes:
  root:
    name: dev_root
