name: dev
services:
  dev:
    container_name: dev
    hostname: dev
    image: ghcr.io/synhi/dev-environment:latest
    network_mode: bridge
    restart: unless-stopped
    tty: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: root
        target: /root
        volume: {}
volumes:
  root:
    name: dev_root
