services:
  dev:
    image: "ghcr.io/synhi/dev-environment:latest"
    container_name: "dev"
    restart: "unless-stopped"
    hostname: "dev"
    network_mode: "bridge"
    volumes:
      - workspace:/workspace

volumes:
  workspace:
    name: workspace
