version: "3.9"

volumes:
  workspace:
    name: workspace

services:
  dev:
    image: "ghcr.io/synhi/dev-environment:latest"
    container_name: "dev"
    restart: "unless-stopped"
    hostname: "dev"
    network_mode: "bridge"
    environment:
      - SHELL=/usr/bin/zsh
      - TZ=Asia/Shanghai
    volumes:
      - workspace:/workspace
