version: "3.9"

volumes:
  root:
    name: dev-root

services:
  dev:
    image: "ghcr.io/synhi/dev-environment:latest"
    container_name: "dev"
    restart: "unless-stopped"
    hostname: "dev"
    network_mode: "bridge"
    environment:
      - TZ=Asia/Shanghai
      - SHELL=/bin/zsh
    volumes:
      - root:/root
