version: "3.9"
services:
  dev:
    image: "ghcr.io/synhi/dev-environment:latest"
    container_name: "dev-environment"
    restart: "unless-stopped"
    hostname: "dev-environment"
    network_mode: "bridge"
    environment:
      - TZ=Asia/Shanghai
