version: "3.9"
services:
  dev-environment:
    image: "shynhan/dev-environment:latest"
    container_name: "dev-environment"
    restart: "unless-stopped"
    hostname: "dev-environment"
    network_mode: "bridge"
