version: "3.9"

volumes:
  root:
    name: dev-root
  # workspace:
  #   name: dev-workspace
  # vscode:
  #   name: dev-vscode
  # go:
  #   name: dev-go

services:
  dev:
    image: "ghcr.io/synhi/dev-environment:latest"
    container_name: "dev-environment"
    restart: "unless-stopped"
    hostname: "dev-environment"
    network_mode: "bridge"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - root:/root
      # - workspace:/workspace
      # - vscode:/root/.vscode-server
      # - go:/root/go
